// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const applicationMetrics = `-- name: ApplicationMetrics :many
SELECT date_trunc('day', s.created_at, 'UTC')::timestamptz AS day,
       s.scorer, avg(s.value)::float8 AS mean,
       avg(CASE WHEN s.passed THEN 1.0 ELSE 0.0 END)::float8 AS pass_rate,
       count(*)::bigint AS n
FROM scores s
LEFT JOIN traces t ON t.id = s.trace_id
LEFT JOIN eval_runs r ON r.id = s.eval_run_id
WHERE coalesce(t.application_id, r.application_id) = $1::uuid
  AND s.created_at >= $2 AND s.created_at < $3
  AND ($4::text = '' OR s.scorer = $4)
GROUP BY day, s.scorer
ORDER BY day, s.scorer
`

type ApplicationMetricsParams struct {
	ApplicationID uuid.UUID
	StartTime     pgtype.Timestamptz
	EndTime       pgtype.Timestamptz
	Scorer        string
}

type ApplicationMetricsRow struct {
	Day      pgtype.Timestamptz
	Scorer   string
	Mean     float64
	PassRate float64
	N        int64
}

func (q *Queries) ApplicationMetrics(ctx context.Context, arg ApplicationMetricsParams) ([]ApplicationMetricsRow, error) {
	rows, err := q.db.Query(ctx, applicationMetrics,
		arg.ApplicationID,
		arg.StartTime,
		arg.EndTime,
		arg.Scorer,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationMetricsRow
	for rows.Next() {
		var i ApplicationMetricsRow
		if err := rows.Scan(
			&i.Day,
			&i.Scorer,
			&i.Mean,
			&i.PassRate,
			&i.N,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationScores = `-- name: ListApplicationScores :many
SELECT s.id, s.scorer, s.scorer_config_id, s.value, s.threshold, s.passed, s.rationale, s.details, s.prompt_template_id, s.judge_model, s.judge_provider, s.judge_tokens, s.eval_run_id, s.dataset_item_id, s.created_at, s.trace_id, s.span_id, s.span_start_time, s.judged_input, s.judged_output, s.judged_context, s.judged_reference FROM scores s
LEFT JOIN traces t ON t.id = s.trace_id
LEFT JOIN eval_runs r ON r.id = s.eval_run_id
WHERE coalesce(t.application_id, r.application_id) = $1::uuid
  AND s.created_at >= $2 AND s.created_at < $3
  AND ($4::text = '' OR s.scorer = $4)
  AND (NOT $5::boolean OR s.passed = $6::boolean)
  AND (NOT $7::boolean
       OR (s.created_at, s.id) > ($8::timestamptz, $9::bigint))
ORDER BY s.created_at, s.id LIMIT $10
`

type ListApplicationScoresParams struct {
	ApplicationID uuid.UUID
	StartTime     pgtype.Timestamptz
	EndTime       pgtype.Timestamptz
	Scorer        string
	FilterPassed  bool
	Passed        bool
	HasCursor     bool
	CursorTime    pgtype.Timestamptz
	CursorID      int64
	PageSize      int32
}

func (q *Queries) ListApplicationScores(ctx context.Context, arg ListApplicationScoresParams) ([]Score, error) {
	rows, err := q.db.Query(ctx, listApplicationScores,
		arg.ApplicationID,
		arg.StartTime,
		arg.EndTime,
		arg.Scorer,
		arg.FilterPassed,
		arg.Passed,
		arg.HasCursor,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Score
	for rows.Next() {
		var i Score
		if err := rows.Scan(
			&i.ID,
			&i.Scorer,
			&i.ScorerConfigID,
			&i.Value,
			&i.Threshold,
			&i.Passed,
			&i.Rationale,
			&i.Details,
			&i.PromptTemplateID,
			&i.JudgeModel,
			&i.JudgeProvider,
			&i.JudgeTokens,
			&i.EvalRunID,
			&i.DatasetItemID,
			&i.CreatedAt,
			&i.TraceID,
			&i.SpanID,
			&i.SpanStartTime,
			&i.JudgedInput,
			&i.JudgedOutput,
			&i.JudgedContext,
			&i.JudgedReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
