// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, project_id, name, key_hash, key_prefix)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, key_hash, key_prefix, last_used_at, revoked_at,
          created_at, updated_at
`

type CreateAPIKeyParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
	Name      string
	KeyHash   []byte
	KeyPrefix string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAPIKeyByHash = `-- name: GetActiveAPIKeyByHash :one
SELECT id, project_id, name, key_hash, key_prefix, last_used_at, revoked_at,
       created_at, updated_at
FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveAPIKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getActiveAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, project_id, name, key_hash, key_prefix, last_used_at, revoked_at,
       created_at, updated_at
FROM api_keys
WHERE project_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListAPIKeys(ctx context.Context, projectID uuid.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = now(), updated_at = now()
WHERE id = $1 AND project_id = $2 AND revoked_at IS NULL
RETURNING id
`

type RevokeAPIKeyParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.ProjectID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
