// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createApplication = `-- name: CreateApplication :one
INSERT INTO applications (
    id, project_id, name, slug, config, auto_score_scorers, target_endpoint
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, name, slug, config, auto_score_scorers, target_endpoint,
          created_at, updated_at
`

type CreateApplicationParams struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	Name             string
	Slug             string
	Config           json.RawMessage
	AutoScoreScorers []string
	TargetEndpoint   []byte
}

func (q *Queries) CreateApplication(ctx context.Context, arg CreateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, createApplication,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Slug,
		arg.Config,
		arg.AutoScoreScorers,
		arg.TargetEndpoint,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.AutoScoreScorers,
		&i.TargetEndpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteApplication = `-- name: DeleteApplication :one
DELETE FROM applications
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteApplication(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteApplication, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getApplication = `-- name: GetApplication :one
SELECT id, project_id, name, slug, config, auto_score_scorers, target_endpoint,
       created_at, updated_at
FROM applications
WHERE id = $1
`

func (q *Queries) GetApplication(ctx context.Context, id uuid.UUID) (Application, error) {
	row := q.db.QueryRow(ctx, getApplication, id)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.AutoScoreScorers,
		&i.TargetEndpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationByProjectSlug = `-- name: GetApplicationByProjectSlug :one
SELECT id, project_id, name, slug, config, auto_score_scorers, target_endpoint,
       created_at, updated_at
FROM applications
WHERE project_id = $1 AND slug = $2
`

type GetApplicationByProjectSlugParams struct {
	ProjectID uuid.UUID
	Slug      string
}

func (q *Queries) GetApplicationByProjectSlug(ctx context.Context, arg GetApplicationByProjectSlugParams) (Application, error) {
	row := q.db.QueryRow(ctx, getApplicationByProjectSlug, arg.ProjectID, arg.Slug)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.AutoScoreScorers,
		&i.TargetEndpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplications = `-- name: ListApplications :many
SELECT id, project_id, name, slug, config, auto_score_scorers, target_endpoint,
       created_at, updated_at
FROM applications
ORDER BY created_at, id
`

func (q *Queries) ListApplications(ctx context.Context) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Config,
			&i.AutoScoreScorers,
			&i.TargetEndpoint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByProject = `-- name: ListApplicationsByProject :many
SELECT id, project_id, name, slug, config, auto_score_scorers, target_endpoint,
       created_at, updated_at
FROM applications
WHERE project_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListApplicationsByProject(ctx context.Context, projectID uuid.UUID) ([]Application, error) {
	rows, err := q.db.Query(ctx, listApplicationsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Application
	for rows.Next() {
		var i Application
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Slug,
			&i.Config,
			&i.AutoScoreScorers,
			&i.TargetEndpoint,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApplication = `-- name: UpdateApplication :one
UPDATE applications
SET name = $2,
    slug = $3,
    config = $4,
    auto_score_scorers = $5,
    target_endpoint = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, name, slug, config, auto_score_scorers, target_endpoint,
          created_at, updated_at
`

type UpdateApplicationParams struct {
	ID               uuid.UUID
	Name             string
	Slug             string
	Config           json.RawMessage
	AutoScoreScorers []string
	TargetEndpoint   []byte
}

func (q *Queries) UpdateApplication(ctx context.Context, arg UpdateApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, updateApplication,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Config,
		arg.AutoScoreScorers,
		arg.TargetEndpoint,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Slug,
		&i.Config,
		&i.AutoScoreScorers,
		&i.TargetEndpoint,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
