// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"
)

const healthCheck = `-- name: HealthCheck :one
SELECT true
`

func (q *Queries) HealthCheck(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, healthCheck)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
