// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
WITH candidate AS (
    SELECT id
    FROM jobs
    WHERE status = 'pending' AND run_after <= now() AND attempts < max_attempts
    ORDER BY run_after ASC, id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE jobs j
SET status = 'running', attempts = attempts + 1, locked_by = $1,
    locked_at = now(),
    lease_expires_at = now() + ($2::double precision * interval '1 second'),
    updated_at = now()
FROM candidate
WHERE j.id = candidate.id
RETURNING j.id, j.kind, j.eval_run_id, j.status, j.run_after, j.attempts, j.max_attempts, j.locked_by, j.locked_at, j.lease_expires_at, j.last_error, j.created_at, j.updated_at, j.trace_id, j.scorer
`

type ClaimJobParams struct {
	WorkerID     pgtype.Text
	LeaseSeconds float64
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.WorkerID, arg.LeaseSeconds)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.EvalRunID,
		&i.Status,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TraceID,
		&i.Scorer,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :one
WITH owned_job AS MATERIALIZED (
	    SELECT j.id, j.kind, j.eval_run_id
    FROM jobs j
    WHERE j.id = $1 AND j.status = 'running'
      AND j.locked_by = $2 AND j.lease_expires_at > now()
    FOR UPDATE
),
aggregates AS (
    SELECT
        COALESCE(jsonb_object_agg(scorer, aggregate), '{}'::jsonb) AS value
    FROM (
        SELECT
            scorer,
            jsonb_build_object(
                'n', count(*),
                'mean', avg(value),
                'pass_rate', avg(CASE WHEN passed THEN 1.0 ELSE 0.0 END)
            ) AS aggregate
        FROM scores
        WHERE eval_run_id = (SELECT eval_run_id FROM owned_job)
        GROUP BY scorer
    ) scorer_aggregates
),
finalized_run AS (
    UPDATE eval_runs er
    SET status = CASE
            WHEN EXISTS (
                SELECT 1 FROM eval_run_items eri
                WHERE eri.eval_run_id = er.id AND eri.status = 'succeeded'
            ) THEN 'succeeded'
            ELSE 'failed'
        END,
        aggregates = aggregates.value,
        succeeded_items = (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status = 'succeeded'
        ),
        failed_items = (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status = 'failed'
        ),
        canceled_items = (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status = 'canceled'
        ),
        finished_at = now(), updated_at = now()
    FROM owned_job, aggregates
    WHERE er.id = owned_job.eval_run_id AND er.status = 'running'
      AND NOT EXISTS (
          SELECT 1 FROM eval_run_items eri
          WHERE eri.eval_run_id = er.id AND eri.status IN ('pending', 'running')
      )
    RETURNING er.id
)
UPDATE jobs j
SET status = 'succeeded', locked_by = NULL, locked_at = NULL, lease_expires_at = NULL,
	    updated_at = now()
FROM owned_job
WHERE j.id = owned_job.id
	  AND (owned_job.kind = 'scoring_task' OR EXISTS (SELECT 1 FROM finalized_run))
RETURNING j.id
`

type CompleteJobParams struct {
	ID       uuid.UUID
	WorkerID pgtype.Text
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, completeJob, arg.ID, arg.WorkerID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createEvalRunJob = `-- name: CreateEvalRunJob :one
INSERT INTO jobs (id, kind, eval_run_id, status, max_attempts)
VALUES ($1, 'eval_run', $2, 'pending', $3)
RETURNING id, kind, eval_run_id, status, run_after, attempts, max_attempts, locked_by, locked_at, lease_expires_at, last_error, created_at, updated_at, trace_id, scorer
`

type CreateEvalRunJobParams struct {
	ID          uuid.UUID
	EvalRunID   pgtype.UUID
	MaxAttempts int32
}

func (q *Queries) CreateEvalRunJob(ctx context.Context, arg CreateEvalRunJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createEvalRunJob, arg.ID, arg.EvalRunID, arg.MaxAttempts)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.EvalRunID,
		&i.Status,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TraceID,
		&i.Scorer,
	)
	return i, err
}

const createScoringTask = `-- name: CreateScoringTask :one
INSERT INTO jobs (id, kind, trace_id, scorer, status, max_attempts)
VALUES ($1, 'scoring_task', $2, $3, 'pending', $4)
ON CONFLICT (trace_id, scorer) WHERE kind = 'scoring_task' DO NOTHING
RETURNING id, kind, eval_run_id, status, run_after, attempts, max_attempts, locked_by, locked_at, lease_expires_at, last_error, created_at, updated_at, trace_id, scorer
`

type CreateScoringTaskParams struct {
	ID          uuid.UUID
	TraceID     pgtype.UUID
	Scorer      pgtype.Text
	MaxAttempts int32
}

func (q *Queries) CreateScoringTask(ctx context.Context, arg CreateScoringTaskParams) (Job, error) {
	row := q.db.QueryRow(ctx, createScoringTask,
		arg.ID,
		arg.TraceID,
		arg.Scorer,
		arg.MaxAttempts,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.EvalRunID,
		&i.Status,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TraceID,
		&i.Scorer,
	)
	return i, err
}

const exhaustJob = `-- name: ExhaustJob :one
WITH exhausted_job AS (
    UPDATE jobs j
    SET status = 'failed', last_error = $1, locked_by = NULL,
        locked_at = NULL, lease_expires_at = NULL, updated_at = now()
    WHERE j.id = $2 AND j.status = 'running'
      AND j.locked_by = $3 AND j.lease_expires_at > now()
    RETURNING j.id, j.eval_run_id
),
failed_run AS (
    UPDATE eval_runs er
    SET status = 'failed', error = $1,
        succeeded_items = (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status = 'succeeded'
        ),
        failed_items = er.total_items - (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status IN ('succeeded', 'canceled')
        ),
        canceled_items = (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status = 'canceled'
        ),
        finished_at = now(), updated_at = now()
    FROM exhausted_job
    WHERE er.id = exhausted_job.eval_run_id AND er.status IN ('pending', 'running')
    RETURNING er.id
),
failed_items AS (
    UPDATE eval_run_items eri
    SET status = 'failed', error = $1, finished_at = now(), updated_at = now()
    FROM failed_run
    WHERE eri.eval_run_id = failed_run.id AND eri.status IN ('pending', 'running')
)
SELECT id FROM exhausted_job
`

type ExhaustJobParams struct {
	LastError pgtype.Text
	JobID     uuid.UUID
	WorkerID  pgtype.Text
}

func (q *Queries) ExhaustJob(ctx context.Context, arg ExhaustJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, exhaustJob, arg.LastError, arg.JobID, arg.WorkerID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const heartbeatJob = `-- name: HeartbeatJob :one
UPDATE jobs
SET lease_expires_at = now() + ($1::double precision * interval '1 second'),
    updated_at = now()
WHERE id = $2 AND status = 'running' AND locked_by = $3
  AND lease_expires_at > now()
RETURNING id
`

type HeartbeatJobParams struct {
	LeaseSeconds float64
	ID           uuid.UUID
	WorkerID     pgtype.Text
}

func (q *Queries) HeartbeatJob(ctx context.Context, arg HeartbeatJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, heartbeatJob, arg.LeaseSeconds, arg.ID, arg.WorkerID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listTraceScoringTasks = `-- name: ListTraceScoringTasks :many
SELECT id, kind, eval_run_id, status, run_after, attempts, max_attempts, locked_by, locked_at, lease_expires_at, last_error, created_at, updated_at, trace_id, scorer FROM jobs
WHERE kind = 'scoring_task' AND trace_id = $1
ORDER BY scorer
`

func (q *Queries) ListTraceScoringTasks(ctx context.Context, traceID pgtype.UUID) ([]Job, error) {
	rows, err := q.db.Query(ctx, listTraceScoringTasks, traceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EvalRunID,
			&i.Status,
			&i.RunAfter,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LockedBy,
			&i.LockedAt,
			&i.LeaseExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TraceID,
			&i.Scorer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockJobTableForDelete = `-- name: LockJobTableForDelete :exec
LOCK TABLE jobs IN EXCLUSIVE MODE
`

func (q *Queries) LockJobTableForDelete(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockJobTableForDelete)
	return err
}

const lockJobTableForWrite = `-- name: LockJobTableForWrite :exec
LOCK TABLE jobs IN ROW EXCLUSIVE MODE
`

func (q *Queries) LockJobTableForWrite(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockJobTableForWrite)
	return err
}

const lockOwnedJob = `-- name: LockOwnedJob :one
SELECT id
FROM jobs
WHERE id = $1 AND status = 'running' AND locked_by = $2
  AND lease_expires_at > now()
FOR UPDATE
`

type LockOwnedJobParams struct {
	ID       uuid.UUID
	WorkerID pgtype.Text
}

func (q *Queries) LockOwnedJob(ctx context.Context, arg LockOwnedJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockOwnedJob, arg.ID, arg.WorkerID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const reapExpiredJobs = `-- name: ReapExpiredJobs :one
WITH candidates AS MATERIALIZED (
    SELECT id
    FROM jobs
    WHERE status = 'running' AND lease_expires_at < now()
    ORDER BY id
    FOR UPDATE SKIP LOCKED
),
expired AS (
    UPDATE jobs
    SET status = CASE WHEN attempts >= max_attempts THEN 'failed' ELSE 'pending' END,
        run_after = now(),
        last_error = CASE
            WHEN attempts >= max_attempts THEN 'job lease expired after maximum attempts'
            ELSE last_error
        END,
        locked_by = NULL, locked_at = NULL, lease_expires_at = NULL, updated_at = now()
    WHERE id IN (SELECT id FROM candidates)
    RETURNING id, eval_run_id, attempts, max_attempts
),
failed_runs AS (
    UPDATE eval_runs er
    SET status = 'failed', error = 'job lease expired after maximum attempts',
        succeeded_items = (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status = 'succeeded'
        ),
        failed_items = er.total_items - (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status IN ('succeeded', 'canceled')
        ),
        canceled_items = (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status = 'canceled'
        ),
        finished_at = now(), updated_at = now()
    FROM expired
    WHERE er.id = expired.eval_run_id AND expired.attempts >= expired.max_attempts
      AND er.status IN ('pending', 'running')
    RETURNING er.id
),
failed_items AS (
    UPDATE eval_run_items eri
    SET status = 'failed', error = 'job lease expired after maximum attempts',
        finished_at = now(), updated_at = now()
    FROM failed_runs
    WHERE eri.eval_run_id = failed_runs.id AND eri.status IN ('pending', 'running')
    RETURNING eri.eval_run_id
),
reset_items AS (
    UPDATE eval_run_items eri
    SET status = 'pending', started_at = NULL, error = NULL, updated_at = now()
    FROM expired
    WHERE eri.eval_run_id = expired.eval_run_id
      AND expired.attempts < expired.max_attempts AND eri.status = 'running'
    RETURNING eri.eval_run_id
)
SELECT
    (SELECT count(*) FROM expired)::integer AS reaped_jobs,
    (SELECT count(*) FROM failed_items)::integer AS failed_items,
    (SELECT count(*) FROM reset_items)::integer AS reset_items
`

type ReapExpiredJobsRow struct {
	ReapedJobs  int32
	FailedItems int32
	ResetItems  int32
}

func (q *Queries) ReapExpiredJobs(ctx context.Context) (ReapExpiredJobsRow, error) {
	row := q.db.QueryRow(ctx, reapExpiredJobs)
	var i ReapExpiredJobsRow
	err := row.Scan(&i.ReapedJobs, &i.FailedItems, &i.ResetItems)
	return i, err
}

const refreshScoringTask = `-- name: RefreshScoringTask :one
INSERT INTO jobs (id, kind, trace_id, scorer, status, max_attempts)
VALUES ($1, 'scoring_task', $2, $3, 'pending', $4)
ON CONFLICT (trace_id, scorer) WHERE kind = 'scoring_task' DO UPDATE
SET status = CASE WHEN jobs.status = 'running' THEN 'running' ELSE 'pending' END,
    attempts = CASE WHEN jobs.status = 'running' THEN jobs.attempts ELSE 0 END,
    run_after = CASE WHEN jobs.status = 'running' THEN jobs.run_after ELSE now() END,
    locked_by = CASE WHEN jobs.status = 'running' THEN jobs.locked_by ELSE NULL END,
    locked_at = CASE WHEN jobs.status = 'running' THEN jobs.locked_at ELSE NULL END,
    lease_expires_at = CASE
        WHEN jobs.status = 'running' THEN jobs.lease_expires_at ELSE NULL
    END,
    last_error = CASE WHEN jobs.status = 'running' THEN jobs.last_error ELSE NULL END,
    updated_at = now()
RETURNING jobs.id, jobs.kind, jobs.eval_run_id, jobs.status, jobs.run_after, jobs.attempts, jobs.max_attempts, jobs.locked_by, jobs.locked_at, jobs.lease_expires_at, jobs.last_error, jobs.created_at, jobs.updated_at, jobs.trace_id, jobs.scorer
`

type RefreshScoringTaskParams struct {
	ID          uuid.UUID
	TraceID     pgtype.UUID
	Scorer      pgtype.Text
	MaxAttempts int32
}

func (q *Queries) RefreshScoringTask(ctx context.Context, arg RefreshScoringTaskParams) (Job, error) {
	row := q.db.QueryRow(ctx, refreshScoringTask,
		arg.ID,
		arg.TraceID,
		arg.Scorer,
		arg.MaxAttempts,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.EvalRunID,
		&i.Status,
		&i.RunAfter,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockedAt,
		&i.LeaseExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TraceID,
		&i.Scorer,
	)
	return i, err
}

const releaseWorkerJobs = `-- name: ReleaseWorkerJobs :one
WITH candidates AS MATERIALIZED (
    SELECT j.id
    FROM jobs j
    WHERE j.status = 'running' AND j.locked_by = $1
    ORDER BY j.id
    FOR UPDATE OF j
),
released AS (
    UPDATE jobs
    SET status = CASE WHEN attempts >= max_attempts THEN 'failed' ELSE 'pending' END,
        run_after = now(),
        last_error = CASE
            WHEN attempts >= max_attempts THEN 'worker stopped after maximum attempts'
            ELSE last_error
        END,
        locked_by = NULL, locked_at = NULL,
        lease_expires_at = NULL, updated_at = now()
    WHERE id IN (SELECT id FROM candidates)
    RETURNING eval_run_id, attempts, max_attempts
),
failed_runs AS (
    UPDATE eval_runs er
    SET status = 'failed', error = 'worker stopped after maximum attempts',
        succeeded_items = (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status = 'succeeded'
        ),
        failed_items = er.total_items - (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status IN ('succeeded', 'canceled')
        ),
        canceled_items = (
            SELECT count(*) FROM eval_run_items eri
            WHERE eri.eval_run_id = er.id AND eri.status = 'canceled'
        ),
        finished_at = now(), updated_at = now()
    FROM released
    WHERE er.id = released.eval_run_id AND released.attempts >= released.max_attempts
      AND er.status IN ('pending', 'running')
    RETURNING er.id
),
failed_items AS (
    UPDATE eval_run_items eri
    SET status = 'failed', error = 'worker stopped after maximum attempts',
        finished_at = now(), updated_at = now()
    FROM failed_runs
    WHERE eri.eval_run_id = failed_runs.id AND eri.status IN ('pending', 'running')
    RETURNING eri.eval_run_id
),
reset_items AS (
    UPDATE eval_run_items eri
    SET status = 'pending', started_at = NULL, error = NULL, updated_at = now()
    FROM released
    WHERE eri.eval_run_id = released.eval_run_id
      AND released.attempts < released.max_attempts AND eri.status = 'running'
    RETURNING eri.eval_run_id
)
SELECT
    (SELECT count(*) FROM released)::integer AS released_jobs,
    (SELECT count(*) FROM failed_items)::integer AS failed_items,
    (SELECT count(*) FROM reset_items)::integer AS reset_items
`

type ReleaseWorkerJobsRow struct {
	ReleasedJobs int32
	FailedItems  int32
	ResetItems   int32
}

func (q *Queries) ReleaseWorkerJobs(ctx context.Context, workerID pgtype.Text) (ReleaseWorkerJobsRow, error) {
	row := q.db.QueryRow(ctx, releaseWorkerJobs, workerID)
	var i ReleaseWorkerJobsRow
	err := row.Scan(&i.ReleasedJobs, &i.FailedItems, &i.ResetItems)
	return i, err
}

const retryJob = `-- name: RetryJob :one
WITH retried_job AS (
    UPDATE jobs j
    SET status = 'pending', run_after = now() + (
            $1::double precision * interval '1 second'
        ),
        last_error = $2, locked_by = NULL, locked_at = NULL,
        lease_expires_at = NULL, updated_at = now()
    WHERE j.id = $3 AND j.status = 'running'
      AND j.locked_by = $4 AND j.lease_expires_at > now()
    RETURNING j.id, j.eval_run_id
),
reset_items AS (
    UPDATE eval_run_items eri
    SET status = 'pending', started_at = NULL, error = NULL, updated_at = now()
    FROM retried_job
    WHERE eri.eval_run_id = retried_job.eval_run_id AND eri.status = 'running'
)
SELECT id FROM retried_job
`

type RetryJobParams struct {
	DelaySeconds float64
	LastError    pgtype.Text
	ID           uuid.UUID
	WorkerID     pgtype.Text
}

func (q *Queries) RetryJob(ctx context.Context, arg RetryJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, retryJob,
		arg.DelaySeconds,
		arg.LastError,
		arg.ID,
		arg.WorkerID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
