// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, judge_config)
VALUES ($1, $2, $3)
RETURNING id, name, judge_config, created_at, updated_at
`

type CreateProjectParams struct {
	ID          uuid.UUID
	Name        string
	JudgeConfig []byte
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.ID, arg.Name, arg.JudgeConfig)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.JudgeConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
DELETE FROM projects
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteProject(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, deleteProject, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, judge_config, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.JudgeConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, judge_config, created_at, updated_at
FROM projects
ORDER BY created_at, id
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.JudgeConfig,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, judge_config = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, judge_config, created_at, updated_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID
	Name        string
	JudgeConfig []byte
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.JudgeConfig)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.JudgeConfig,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
