// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scorer_configs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getScorerConfig = `-- name: GetScorerConfig :one
SELECT id, application_id, scorer, enabled, threshold, judge_config, prompt_template_id,
       created_at, updated_at
FROM scorer_configs
WHERE application_id = $1 AND scorer = $2
`

type GetScorerConfigParams struct {
	ApplicationID uuid.UUID
	Scorer        string
}

func (q *Queries) GetScorerConfig(ctx context.Context, arg GetScorerConfigParams) (ScorerConfig, error) {
	row := q.db.QueryRow(ctx, getScorerConfig, arg.ApplicationID, arg.Scorer)
	var i ScorerConfig
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Scorer,
		&i.Enabled,
		&i.Threshold,
		&i.JudgeConfig,
		&i.PromptTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScorerConfigs = `-- name: ListScorerConfigs :many
SELECT id, application_id, scorer, enabled, threshold, judge_config, prompt_template_id,
       created_at, updated_at
FROM scorer_configs
WHERE application_id = $1
ORDER BY scorer
`

func (q *Queries) ListScorerConfigs(ctx context.Context, applicationID uuid.UUID) ([]ScorerConfig, error) {
	rows, err := q.db.Query(ctx, listScorerConfigs, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScorerConfig
	for rows.Next() {
		var i ScorerConfig
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.Scorer,
			&i.Enabled,
			&i.Threshold,
			&i.JudgeConfig,
			&i.PromptTemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScorerConfig = `-- name: UpsertScorerConfig :one
INSERT INTO scorer_configs (
    id, application_id, scorer, enabled, threshold, judge_config, prompt_template_id
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7
)
ON CONFLICT (application_id, scorer) DO UPDATE
SET enabled = EXCLUDED.enabled,
    threshold = EXCLUDED.threshold,
    judge_config = EXCLUDED.judge_config,
    prompt_template_id = EXCLUDED.prompt_template_id,
    updated_at = now()
RETURNING id, application_id, scorer, enabled, threshold, judge_config, prompt_template_id,
          created_at, updated_at
`

type UpsertScorerConfigParams struct {
	ID               uuid.UUID
	ApplicationID    uuid.UUID
	Scorer           string
	Enabled          bool
	Threshold        pgtype.Numeric
	JudgeConfig      []byte
	PromptTemplateID pgtype.Text
}

func (q *Queries) UpsertScorerConfig(ctx context.Context, arg UpsertScorerConfigParams) (ScorerConfig, error) {
	row := q.db.QueryRow(ctx, upsertScorerConfig,
		arg.ID,
		arg.ApplicationID,
		arg.Scorer,
		arg.Enabled,
		arg.Threshold,
		arg.JudgeConfig,
		arg.PromptTemplateID,
	)
	var i ScorerConfig
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.Scorer,
		&i.Enabled,
		&i.Threshold,
		&i.JudgeConfig,
		&i.PromptTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
