// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listProjectSessionTurns = `-- name: ListProjectSessionTurns :many
SELECT t.id, t.root_name, t.start_time, t.end_time, t.status, t.span_count,
       t.total_tokens, t.attributes
FROM traces t
JOIN applications a ON a.id = t.application_id
WHERE a.project_id = $1
  AND t.application_id = $2
  AND t.session_id = $3
ORDER BY t.start_time, t.id
LIMIT $4
`

type ListProjectSessionTurnsParams struct {
	ProjectID     uuid.UUID
	ApplicationID uuid.UUID
	SessionID     pgtype.Text
	PageSize      int32
}

type ListProjectSessionTurnsRow struct {
	ID          uuid.UUID
	RootName    string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
	SpanCount   int32
	TotalTokens int64
	Attributes  json.RawMessage
}

func (q *Queries) ListProjectSessionTurns(ctx context.Context, arg ListProjectSessionTurnsParams) ([]ListProjectSessionTurnsRow, error) {
	rows, err := q.db.Query(ctx, listProjectSessionTurns,
		arg.ProjectID,
		arg.ApplicationID,
		arg.SessionID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectSessionTurnsRow
	for rows.Next() {
		var i ListProjectSessionTurnsRow
		if err := rows.Scan(
			&i.ID,
			&i.RootName,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.SpanCount,
			&i.TotalTokens,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectSessionTurnsAfterCursor = `-- name: ListProjectSessionTurnsAfterCursor :many
SELECT t.id, t.root_name, t.start_time, t.end_time, t.status, t.span_count,
       t.total_tokens, t.attributes
FROM traces t
JOIN applications a ON a.id = t.application_id
WHERE a.project_id = $1
  AND t.application_id = $2
  AND t.session_id = $3
  AND (t.start_time, t.id) > (
      $4::timestamptz, $5::uuid
  )
ORDER BY t.start_time, t.id
LIMIT $6
`

type ListProjectSessionTurnsAfterCursorParams struct {
	ProjectID     uuid.UUID
	ApplicationID uuid.UUID
	SessionID     pgtype.Text
	CursorTime    pgtype.Timestamptz
	CursorID      uuid.UUID
	PageSize      int32
}

type ListProjectSessionTurnsAfterCursorRow struct {
	ID          uuid.UUID
	RootName    string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
	SpanCount   int32
	TotalTokens int64
	Attributes  json.RawMessage
}

func (q *Queries) ListProjectSessionTurnsAfterCursor(ctx context.Context, arg ListProjectSessionTurnsAfterCursorParams) ([]ListProjectSessionTurnsAfterCursorRow, error) {
	rows, err := q.db.Query(ctx, listProjectSessionTurnsAfterCursor,
		arg.ProjectID,
		arg.ApplicationID,
		arg.SessionID,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectSessionTurnsAfterCursorRow
	for rows.Next() {
		var i ListProjectSessionTurnsAfterCursorRow
		if err := rows.Scan(
			&i.ID,
			&i.RootName,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.SpanCount,
			&i.TotalTokens,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectSessions = `-- name: ListProjectSessions :many
WITH sessions AS (
    SELECT t.session_id, min(t.start_time) AS start_time,
           max(t.end_time) AS end_time, count(*)::bigint AS turn_count,
           (array_agg(t.root_name ORDER BY t.start_time, t.id))[1] AS first_operation,
           (array_agg(t.id ORDER BY t.end_time DESC, t.id DESC))[1] AS last_trace_id
    FROM traces t
    JOIN applications a ON a.id = t.application_id
    WHERE a.project_id = $5
      AND t.application_id = $6
      AND t.session_id IS NOT NULL
      AND t.end_time <= $7::timestamptz
    GROUP BY t.session_id
)
SELECT session_id::text AS session_id, start_time::timestamptz AS start_time,
       end_time::timestamptz AS end_time, turn_count::bigint AS turn_count,
       first_operation::text AS first_operation, last_trace_id::uuid AS last_trace_id
FROM sessions
WHERE NOT $1::boolean OR (end_time, session_id) < (
    $2::timestamptz, $3::text
)
ORDER BY end_time DESC, session_id DESC
LIMIT $4
`

type ListProjectSessionsParams struct {
	HasCursor     bool
	CursorTime    pgtype.Timestamptz
	CursorID      string
	PageSize      int32
	ProjectID     uuid.UUID
	ApplicationID uuid.UUID
	AnchorTime    pgtype.Timestamptz
}

type ListProjectSessionsRow struct {
	SessionID      string
	StartTime      pgtype.Timestamptz
	EndTime        pgtype.Timestamptz
	TurnCount      int64
	FirstOperation string
	LastTraceID    uuid.UUID
}

func (q *Queries) ListProjectSessions(ctx context.Context, arg ListProjectSessionsParams) ([]ListProjectSessionsRow, error) {
	rows, err := q.db.Query(ctx, listProjectSessions,
		arg.HasCursor,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
		arg.ProjectID,
		arg.ApplicationID,
		arg.AnchorTime,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectSessionsRow
	for rows.Next() {
		var i ListProjectSessionsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.StartTime,
			&i.EndTime,
			&i.TurnCount,
			&i.FirstOperation,
			&i.LastTraceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentSessionTurns = `-- name: ListRecentSessionTurns :many
SELECT t.id, t.root_name, t.start_time, t.end_time, t.status, t.span_count,
       t.total_tokens, t.attributes
FROM traces t
JOIN applications a ON a.id = t.application_id
WHERE a.project_id = $1
  AND t.application_id = $2
  AND t.session_id = $3
ORDER BY t.start_time DESC, t.id DESC
LIMIT $4
`

type ListRecentSessionTurnsParams struct {
	ProjectID     uuid.UUID
	ApplicationID uuid.UUID
	SessionID     pgtype.Text
	PageSize      int32
}

type ListRecentSessionTurnsRow struct {
	ID          uuid.UUID
	RootName    string
	StartTime   pgtype.Timestamptz
	EndTime     pgtype.Timestamptz
	Status      string
	SpanCount   int32
	TotalTokens int64
	Attributes  json.RawMessage
}

func (q *Queries) ListRecentSessionTurns(ctx context.Context, arg ListRecentSessionTurnsParams) ([]ListRecentSessionTurnsRow, error) {
	rows, err := q.db.Query(ctx, listRecentSessionTurns,
		arg.ProjectID,
		arg.ApplicationID,
		arg.SessionID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentSessionTurnsRow
	for rows.Next() {
		var i ListRecentSessionTurnsRow
		if err := rows.Scan(
			&i.ID,
			&i.RootName,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.SpanCount,
			&i.TotalTokens,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
