// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: traces.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectTrace = `-- name: GetProjectTrace :one
SELECT traces.id, traces.application_id, traces.otel_trace_id, traces.root_name,
       traces.start_time, traces.end_time, traces.status, traces.span_count,
       traces.total_tokens, traces.total_cost, traces.reference_answer, traces.attributes,
       traces.created_at, traces.updated_at
FROM traces
JOIN applications ON applications.id = traces.application_id
WHERE traces.id = $1 AND applications.project_id = $2
`

type GetProjectTraceParams struct {
	ID        uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetProjectTrace(ctx context.Context, arg GetProjectTraceParams) (Trace, error) {
	row := q.db.QueryRow(ctx, getProjectTrace, arg.ID, arg.ProjectID)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OtelTraceID,
		&i.RootName,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.SpanCount,
		&i.TotalTokens,
		&i.TotalCost,
		&i.ReferenceAnswer,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectTraceSpans = `-- name: ListProjectTraceSpans :many
SELECT spans.id, spans.trace_id, spans.application_id, spans.otel_span_id,
       spans.parent_span_id, spans.name, spans.kind, spans.operation_name,
       spans.start_time, spans.end_time, spans.duration_ms, spans.status_code,
       spans.status_message, spans.is_scorable, spans.scorable_kind, spans.attributes,
       spans.events, spans.input_tokens, spans.output_tokens, spans.reference_answer,
       spans.created_at
FROM spans
JOIN applications ON applications.id = spans.application_id
WHERE spans.trace_id = $1 AND applications.project_id = $2
ORDER BY spans.start_time, spans.id
`

type ListProjectTraceSpansParams struct {
	TraceID   uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) ListProjectTraceSpans(ctx context.Context, arg ListProjectTraceSpansParams) ([]Span, error) {
	rows, err := q.db.Query(ctx, listProjectTraceSpans, arg.TraceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Span
	for rows.Next() {
		var i Span
		if err := rows.Scan(
			&i.ID,
			&i.TraceID,
			&i.ApplicationID,
			&i.OtelSpanID,
			&i.ParentSpanID,
			&i.Name,
			&i.Kind,
			&i.OperationName,
			&i.StartTime,
			&i.EndTime,
			&i.DurationMs,
			&i.StatusCode,
			&i.StatusMessage,
			&i.IsScorable,
			&i.ScorableKind,
			&i.Attributes,
			&i.Events,
			&i.InputTokens,
			&i.OutputTokens,
			&i.ReferenceAnswer,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTraces = `-- name: ListProjectTraces :many
SELECT traces.id, traces.application_id, traces.otel_trace_id, traces.root_name,
       traces.start_time, traces.end_time, traces.status, traces.span_count,
       traces.total_tokens, traces.total_cost, traces.reference_answer, traces.attributes,
       traces.created_at, traces.updated_at
FROM traces
JOIN applications ON applications.id = traces.application_id
WHERE applications.project_id = $1
  AND (NOT $2::boolean
       OR traces.application_id = $3)
  AND (NOT $4::boolean OR traces.start_time >= $5)
  AND (NOT $6::boolean OR traces.start_time < $7)
  AND (NOT $8::boolean OR traces.status = $9)
  AND (NOT $10::boolean
       OR (traces.start_time, traces.id) < (
           $11::timestamptz,
           $12::uuid
       ))
ORDER BY traces.start_time DESC, traces.id DESC
LIMIT $13
`

type ListProjectTracesParams struct {
	ProjectID         uuid.UUID
	FilterApplication bool
	ApplicationID     uuid.UUID
	FilterStart       bool
	StartTime         pgtype.Timestamptz
	FilterEnd         bool
	EndTime           pgtype.Timestamptz
	FilterStatus      bool
	Status            string
	HasCursor         bool
	CursorTime        pgtype.Timestamptz
	CursorID          uuid.UUID
	PageSize          int32
}

func (q *Queries) ListProjectTraces(ctx context.Context, arg ListProjectTracesParams) ([]Trace, error) {
	rows, err := q.db.Query(ctx, listProjectTraces,
		arg.ProjectID,
		arg.FilterApplication,
		arg.ApplicationID,
		arg.FilterStart,
		arg.StartTime,
		arg.FilterEnd,
		arg.EndTime,
		arg.FilterStatus,
		arg.Status,
		arg.HasCursor,
		arg.CursorTime,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Trace
	for rows.Next() {
		var i Trace
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.OtelTraceID,
			&i.RootName,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.SpanCount,
			&i.TotalTokens,
			&i.TotalCost,
			&i.ReferenceAnswer,
			&i.Attributes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTraceSummary = `-- name: RefreshTraceSummary :one
WITH summary AS (
    SELECT
        spans.trace_id,
        min(spans.start_time) AS start_time,
        max(spans.end_time) AS end_time,
        count(*)::integer AS span_count,
        coalesce(sum(input_tokens + output_tokens), 0)::bigint AS total_tokens,
        max(reference_answer) FILTER (WHERE reference_answer IS NOT NULL) AS reference_answer
    FROM spans
    WHERE spans.trace_id = $1
    GROUP BY spans.trace_id
), root AS (
    SELECT name, status_code, attributes
    FROM spans
    WHERE spans.trace_id = $1
    ORDER BY (parent_span_id IS NULL) DESC, start_time, id
    LIMIT 1
)
UPDATE traces
SET root_name = root.name,
    start_time = summary.start_time,
    end_time = summary.end_time,
    status = root.status_code,
    span_count = summary.span_count,
    total_tokens = summary.total_tokens,
    reference_answer = summary.reference_answer,
    attributes = root.attributes,
    updated_at = now()
FROM summary, root
WHERE traces.id = summary.trace_id
RETURNING traces.id, traces.application_id, traces.otel_trace_id, traces.root_name,
          traces.start_time, traces.end_time, traces.status, traces.span_count,
          traces.total_tokens, traces.total_cost, traces.reference_answer, traces.attributes,
          traces.created_at, traces.updated_at
`

func (q *Queries) RefreshTraceSummary(ctx context.Context, selectedTraceID uuid.UUID) (Trace, error) {
	row := q.db.QueryRow(ctx, refreshTraceSummary, selectedTraceID)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OtelTraceID,
		&i.RootName,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.SpanCount,
		&i.TotalTokens,
		&i.TotalCost,
		&i.ReferenceAnswer,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSpan = `-- name: UpsertSpan :exec
INSERT INTO spans (
    trace_id, application_id, otel_span_id, parent_span_id, name, kind,
    operation_name, start_time, end_time, duration_ms, status_code, status_message,
    is_scorable, scorable_kind, attributes, events, input_tokens, output_tokens,
    reference_answer
)
VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16, $17, $18,
    $19
)
ON CONFLICT (trace_id, otel_span_id, start_time) DO UPDATE
SET application_id = EXCLUDED.application_id,
    parent_span_id = EXCLUDED.parent_span_id,
    name = EXCLUDED.name,
    kind = EXCLUDED.kind,
    operation_name = EXCLUDED.operation_name,
    end_time = EXCLUDED.end_time,
    duration_ms = EXCLUDED.duration_ms,
    status_code = EXCLUDED.status_code,
    status_message = EXCLUDED.status_message,
    is_scorable = EXCLUDED.is_scorable,
    scorable_kind = EXCLUDED.scorable_kind,
    attributes = EXCLUDED.attributes,
    events = EXCLUDED.events,
    input_tokens = EXCLUDED.input_tokens,
    output_tokens = EXCLUDED.output_tokens,
    reference_answer = EXCLUDED.reference_answer
`

type UpsertSpanParams struct {
	TraceID         uuid.UUID
	ApplicationID   uuid.UUID
	OtelSpanID      []byte
	ParentSpanID    []byte
	Name            string
	Kind            string
	OperationName   string
	StartTime       pgtype.Timestamptz
	EndTime         pgtype.Timestamptz
	DurationMs      int64
	StatusCode      string
	StatusMessage   string
	IsScorable      bool
	ScorableKind    string
	Attributes      json.RawMessage
	Events          json.RawMessage
	InputTokens     int64
	OutputTokens    int64
	ReferenceAnswer pgtype.Text
}

func (q *Queries) UpsertSpan(ctx context.Context, arg UpsertSpanParams) error {
	_, err := q.db.Exec(ctx, upsertSpan,
		arg.TraceID,
		arg.ApplicationID,
		arg.OtelSpanID,
		arg.ParentSpanID,
		arg.Name,
		arg.Kind,
		arg.OperationName,
		arg.StartTime,
		arg.EndTime,
		arg.DurationMs,
		arg.StatusCode,
		arg.StatusMessage,
		arg.IsScorable,
		arg.ScorableKind,
		arg.Attributes,
		arg.Events,
		arg.InputTokens,
		arg.OutputTokens,
		arg.ReferenceAnswer,
	)
	return err
}

const upsertTrace = `-- name: UpsertTrace :one
INSERT INTO traces (
    id, application_id, otel_trace_id, root_name, start_time, end_time, status,
    span_count, total_tokens, reference_answer, attributes
)
SELECT
    $1, applications.id, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10
FROM applications
WHERE applications.id = $11
  AND applications.project_id = $12
ON CONFLICT (application_id, otel_trace_id) DO UPDATE
SET updated_at = now()
RETURNING id, application_id, otel_trace_id, root_name, start_time, end_time, status,
          span_count, total_tokens, total_cost, reference_answer, attributes,
          created_at, updated_at
`

type UpsertTraceParams struct {
	ID              uuid.UUID
	OtelTraceID     []byte
	RootName        string
	StartTime       pgtype.Timestamptz
	EndTime         pgtype.Timestamptz
	Status          string
	SpanCount       int32
	TotalTokens     int64
	ReferenceAnswer pgtype.Text
	Attributes      json.RawMessage
	ApplicationID   uuid.UUID
	ProjectID       uuid.UUID
}

func (q *Queries) UpsertTrace(ctx context.Context, arg UpsertTraceParams) (Trace, error) {
	row := q.db.QueryRow(ctx, upsertTrace,
		arg.ID,
		arg.OtelTraceID,
		arg.RootName,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.SpanCount,
		arg.TotalTokens,
		arg.ReferenceAnswer,
		arg.Attributes,
		arg.ApplicationID,
		arg.ProjectID,
	)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OtelTraceID,
		&i.RootName,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.SpanCount,
		&i.TotalTokens,
		&i.TotalCost,
		&i.ReferenceAnswer,
		&i.Attributes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
