package main

import (
	"bytes"
	"encoding/json"
	"os"
	"strings"
	"testing"
)

func TestGenerateOpenAPIIsStableAndComplete(t *testing.T) {
	first, err := generateOpenAPI()
	if err != nil {
		t.Fatalf("generate first OpenAPI document: %v", err)
	}
	second, err := generateOpenAPI()
	if err != nil {
		t.Fatalf("generate second OpenAPI document: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("OpenAPI generation is not byte-stable")
	}
	if !bytes.HasSuffix(first, []byte("\n")) {
		t.Fatal("OpenAPI document does not end with a newline")
	}

	var document generatedDocument
	if err := json.Unmarshal(first, &document); err != nil {
		t.Fatalf("decode generated OpenAPI document: %v", err)
	}
	if document.OpenAPI != "3.1.0" {
		t.Fatalf("OpenAPI version = %q, want 3.1.0", document.OpenAPI)
	}
	assertEvaluationPaths(t, document.Paths)
	assertAdminTraceSecurity(t, document.Paths)
}

func TestRunWritesOpenAPIAndRejectsInvalidPaths(t *testing.T) {
	output := t.TempDir() + "/openapi.json"
	if err := run([]string{"--output", output}); err != nil {
		t.Fatalf("write OpenAPI document: %v", err)
	}
	written, err := os.ReadFile(output)
	if err != nil {
		t.Fatalf("read OpenAPI document: %v", err)
	}
	want, err := generateOpenAPI()
	if err != nil {
		t.Fatalf("generate expected OpenAPI document: %v", err)
	}
	if !bytes.Equal(written, want) {
		t.Fatal("written OpenAPI document differs from generated bytes")
	}

	if err := run([]string{"--output", " "}); err == nil {
		t.Fatal("blank output path succeeded")
	}
	missing := t.TempDir() + "/missing/openapi.json"
	err = run([]string{"--output", missing})
	if err == nil || !strings.Contains(err.Error(), missing) {
		t.Fatalf("missing-parent error = %v, want path-aware error", err)
	}
}

type generatedDocument struct {
	OpenAPI string                                   `json:"openapi"`
	Paths   map[string]map[string]generatedOperation `json:"paths"`
}

type generatedOperation struct {
	Security []map[string][]string `json:"security"`
}

func assertEvaluationPaths(t *testing.T, paths map[string]map[string]generatedOperation) {
	t.Helper()
	expected := []string{
		"/v1/datasets",
		"/v1/datasets/{id}",
		"/v1/datasets/{id}/items",
		"/v1/datasets/{id}/items/{itemId}",
		"/v1/applications/{application_id}/scorers",
		"/v1/applications/{application_id}/scorers/{scorer}",
		"/v1/runs",
		"/v1/runs/{id}",
		"/v1/runs/{id}/items",
		"/v1/runs/{id}/scores",
		"/v1/runs/{id}/cancel",
	}
	for _, path := range expected {
		if _, found := paths[path]; !found {
			t.Errorf("generated OpenAPI is missing path %s", path)
		}
	}
}

func assertAdminTraceSecurity(t *testing.T, paths map[string]map[string]generatedOperation) {
	t.Helper()
	for _, path := range []string{"/v1/traces", "/v1/traces/{id}"} {
		operation := paths[path]["get"]
		found := false
		for _, requirement := range operation.Security {
			if _, found = requirement["adminBearer"]; found {
				break
			}
		}
		if !found {
			t.Errorf("generated OpenAPI GET %s is missing adminBearer security", path)
		}
	}
	deleteOperation := paths["/v1/traces/{id}"]["delete"]
	assertAdminOnlyOperation(t, "DELETE /v1/traces/{id}", deleteOperation)
}

func assertAdminOnlyOperation(
	t *testing.T,
	label string,
	operation generatedOperation,
) {
	t.Helper()
	adminOnly := false
	for _, requirement := range operation.Security {
		if _, found := requirement["adminBearer"]; found {
			adminOnly = true
		}
		if _, found := requirement["projectBearer"]; found {
			t.Errorf("generated OpenAPI %s exposes projectBearer", label)
		}
	}
	if !adminOnly {
		t.Errorf("generated OpenAPI %s is missing adminBearer security", label)
	}
}
